import keyboard

# keyboard.write('python testkeyboard.py')
# keyboard.press('left')
# keyboard.release('left')
# keyboard.press('left')
# keyboard.release('left')
# keyboard.press('left')
# keyboard.release('left')
# keyboard.press('left')
# keyboard.release('left')
# keyboard.press('left')
# keyboard.release('left')
# keyboard.press('up')
# keyboard.release('up')
# keyboard.press('up')
# keyboard.release('up')
# keyboard.press('up')
# keyboard.release('up')
# keyboard.press('up')
# keyboard.release('up')
# keyboard.press('up')
# keyboard.release('up')
# keyboard.press('up')
# keyboard.release('up')